<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260317000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create translation_group + translation tables and seed default EN/PL translations';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('translation_group')) {
            $this->addSql(<<<'SQL'
                CREATE TABLE translation_group (
                    id              INT AUTO_INCREMENT NOT NULL,
                    translation_key VARCHAR(200) NOT NULL,
                    created_at      DATETIME     NOT NULL COMMENT '(DC2Type:datetime_immutable)',
                    updated_at      DATETIME     NOT NULL COMMENT '(DC2Type:datetime_immutable)',
                    UNIQUE INDEX UNQ_TRANSLATION_GROUP_KEY (translation_key),
                    PRIMARY KEY (id)
                ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
            SQL);
        }

        if (!$schema->hasTable('translation')) {
            $this->addSql(<<<'SQL'
                CREATE TABLE translation (
                    id                INT AUTO_INCREMENT NOT NULL,
                    translation_group_id INT NOT NULL,
                    locale            VARCHAR(5)   NOT NULL,
                    translation_value LONGTEXT     NOT NULL,
                    created_at        DATETIME     NOT NULL COMMENT '(DC2Type:datetime_immutable)',
                    updated_at        DATETIME     NOT NULL COMMENT '(DC2Type:datetime_immutable)',
                    UNIQUE INDEX UNQ_LOCALE_GROUP (locale, translation_group_id),
                    INDEX IDX_TRANSLATION_GROUP (translation_group_id),
                    PRIMARY KEY (id)
                ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
            SQL);
            $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_TRANSLATION_GROUP FOREIGN KEY (translation_group_id) REFERENCES translation_group (id) ON DELETE CASCADE');
        }

        $now = date('Y-m-d H:i:s');

        // Keep all seeded translation keys in this single migration.
        // Add future keys here instead of creating additional translation-only migrations.
        $translations = [
            // ── Navigation ───────────────────────────────────────────────────
            ['en', 'nav.brand',       'My Dashboard'],
            ['pl', 'nav.brand',       'Mój Panel'],
            ['en', 'nav.dashboard',   'Dashboard'],
            ['pl', 'nav.dashboard',   'Panel'],
            ['en', 'nav.todos',       'To-Do'],
            ['pl', 'nav.todos',       'Zadania'],
            ['en', 'nav.shopping',    'Shopping'],
            ['pl', 'nav.shopping',    'Zakupy'],
            ['en', 'nav.events',      'My Events'],
            ['pl', 'nav.events',      'Moje Wydarzenia'],
            ['en', 'nav.calendar',    'Calendar'],
            ['pl', 'nav.calendar',    'Kalendarz'],
            ['en', 'nav.map',         'Map'],
            ['pl', 'nav.map',         'Mapa'],
            ['en', 'nav.users',       'Users'],
            ['pl', 'nav.users',       'Użytkownicy'],
            ['en', 'nav.settings',    'Settings'],
            ['pl', 'nav.settings',    'Ustawienia'],
            ['en', 'nav.signOut',     'Sign out'],
            ['pl', 'nav.signOut',     'Wyloguj'],
            ['en', 'nav.language',    'Language'],
            ['pl', 'nav.language',    'Język'],
            ['en', 'login.title',            'My Dashboard'],
            ['pl', 'login.title',            'Mój Panel'],
            ['en', 'login.subtitle',         'Sign in to your account'],
            ['pl', 'login.subtitle',         'Zaloguj się na swoje konto'],
            ['en', 'login.emailLabel',       'Email'],
            ['pl', 'login.emailLabel',       'Email'],
            ['en', 'login.passwordLabel',    'Password'],
            ['pl', 'login.passwordLabel',    'Hasło'],
            ['en', 'login.showPassword',     'Show password'],
            ['pl', 'login.showPassword',     'Pokaż hasło'],
            ['en', 'login.hidePassword',     'Hide password'],
            ['pl', 'login.hidePassword',     'Ukryj hasło'],
            ['en', 'login.signInBtn',        'Sign In'],
            ['pl', 'login.signInBtn',        'Zaloguj się'],
            ['en', 'login.signingIn',        'Signing in…'],
            ['pl', 'login.signingIn',        'Logowanie…'],
            ['en', 'login.requestAccess',    'Request Access'],
            ['pl', 'login.requestAccess',    'Poproś o dostęp'],
            ['en', 'login.accountInfo',      'Account creation is managed by administrators.'],
            ['pl', 'login.accountInfo',      'Tworzenie kont zarządzane jest przez administratorów.'],
            ['en', 'login.requestTitle',     'Request Access'],
            ['pl', 'login.requestTitle',     'Poproś o dostęp'],
            ['en', 'login.backToLogin',      '← Back to login'],
            ['pl', 'login.backToLogin',      '← Powrót do logowania'],
            ['en', 'login.requestSubtitle',  'Send your details to administrator for approval.'],
            ['pl', 'login.requestSubtitle',  'Wyślij swoje dane do administratora w celu zatwierdzenia.'],
            ['en', 'login.firstNameLabel',   'First name (optional)'],
            ['pl', 'login.firstNameLabel',   'Imię (opcjonalnie)'],
            ['en', 'login.lastNameLabel',    'Last name (optional)'],
            ['pl', 'login.lastNameLabel',    'Nazwisko (opcjonalnie)'],
            ['en', 'login.messageLabel',     'Request access message'],
            ['pl', 'login.messageLabel',     'Wiadomość z prośbą o dostęp'],
            ['en', 'login.cancelBtn',        'Cancel'],
            ['pl', 'login.cancelBtn',        'Anuluj'],
            ['en', 'login.sendRequestBtn',   'Send Request'],
            ['pl', 'login.sendRequestBtn',   'Wyślij zgłoszenie'],
            ['en', 'login.sending',          'Sending…'],
            ['pl', 'login.sending',          'Wysyłanie…'],
            ['en', 'settings.title',                  '⚙️ Settings'],
            ['pl', 'settings.title',                  '⚙️ Ustawienia'],
            ['en', 'settings.access',                 '🔐 Access & Roles'],
            ['pl', 'settings.access',                 '🔐 Dostęp i Role'],
            ['en', 'settings.accessSubtitle',         'Manage roles and permissions'],
            ['pl', 'settings.accessSubtitle',         'Zarządzaj rolami i uprawnieniami'],
            ['en', 'settings.jwtSession',             '🪪 JWT Session'],
            ['pl', 'settings.jwtSession',             '🪪 Sesja JWT'],
            ['en', 'settings.jwtSessionSubtitle',     'Configure token expiry time'],
            ['pl', 'settings.jwtSessionSubtitle',     'Konfiguracja czasu ważności tokenu'],
            ['en', 'settings.notifications',          '🔔 Notifications'],
            ['pl', 'settings.notifications',          '🔔 Powiadomienia'],
            ['en', 'settings.notificationsSubtitle',  'Message templates and delivery channels'],
            ['pl', 'settings.notificationsSubtitle',  'Szablony wiadomości i kanały dostarczania'],
            ['en', 'settings.translations',           '🌐 Translations'],
            ['pl', 'settings.translations',           '🌐 Tłumaczenia'],
            ['en', 'settings.translationsSubtitle',   'Manage UI translation keys'],
            ['pl', 'settings.translationsSubtitle',   'Zarządzaj kluczami tłumaczeń'],
            // ── Users ─────────────────────────────────────────────────────────
            ['en', 'users.directory',          'Directory'],
            ['pl', 'users.directory',          'Katalog'],
            ['en', 'users.searchPlaceholder',  'Search by email or name'],
            ['pl', 'users.searchPlaceholder',  'Szukaj po emailu lub nazwie'],
            ['en', 'users.total',              'Total:'],
            ['pl', 'users.total',              'Łącznie:'],
            ['en', 'users.loading',            'Loading users…'],
            ['pl', 'users.loading',            'Ładowanie użytkowników…'],
            ['en', 'users.notFound',           'No users found.'],
            ['pl', 'users.notFound',           'Nie znaleziono użytkowników.'],
            ['en', 'users.email',              'Email'],
            ['pl', 'users.email',              'Email'],
            ['en', 'users.name',               'Name'],
            ['pl', 'users.name',               'Nazwa'],
            ['en', 'users.status',             'Status'],
            ['pl', 'users.status',             'Status'],
            ['en', 'users.role',               'Role'],
            ['pl', 'users.role',               'Rola'],
            ['en', 'users.actions',            'Actions'],
            ['pl', 'users.actions',            'Akcje'],
            ['en', 'users.edit',               'Edit'],
            ['pl', 'users.edit',               'Edytuj'],
            ['en', 'users.delete',             'Delete'],
            ['pl', 'users.delete',             'Usuń'],
            ['en', 'users.addUser',            '+ Add User'],
            ['pl', 'users.addUser',            '+ Dodaj Użytkownika'],
            ['en', 'todo.title',    'My To-Do Lists'],
            ['pl', 'todo.title',    'Moje Listy Zadań'],
            ['en', 'todo.newList',  '+ New List'],
            ['pl', 'todo.newList',  '+ Nowa Lista'],
            ['en', 'todo.empty',    'No to-do lists yet. Create your first!'],
            ['pl', 'todo.empty',    'Brak list zadań. Stwórz swoją pierwszą!'],
            ['en', 'todo.addItem',  'Add item…'],
            ['pl', 'todo.addItem',  'Dodaj element…'],
            ['en', 'todo.dueLabel', 'Due:'],
            ['pl', 'todo.dueLabel', 'Termin:'],
            ['en', 'todo.confirmUndoneTitle', 'Mark task as not completed?'],
            ['pl', 'todo.confirmUndoneTitle', 'Oznaczyć zadanie jako nieukończone?'],
            ['en', 'todo.confirmToggleTitle', 'Mark task as completed?'],
            ['pl', 'todo.confirmToggleTitle', 'Oznaczyć zadanie jako ukończone?'],
            ['en', 'todo.markUndone', 'Mark as active'],
            ['pl', 'todo.markUndone', 'Oznacz jako aktywne'],
            ['en', 'todo.markDone', 'Mark as done'],
            ['pl', 'todo.markDone', 'Oznacz jako zrobione'],
            ['en', 'todo.shareTitle', 'Share task'],
            ['pl', 'todo.shareTitle', 'Udostępnij zadanie'],
            ['en', 'todo.shareTask', 'Share task'],
            ['pl', 'todo.shareTask', 'Udostępnij zadanie'],
            ['en', 'todo.dueDate', 'Due:'],
            ['pl', 'todo.dueDate', 'Termin:'],
            ['en', 'shopping.title',   'Shopping Lists'],
            ['pl', 'shopping.title',   'Listy Zakupów'],
            ['en', 'shopping.newList', '+ New List'],
            ['pl', 'shopping.newList', '+ Nowa Lista'],
            ['en', 'shopping.empty',   'No shopping lists yet.'],
            ['pl', 'shopping.empty',   'Brak list zakupów.'],
            ['en', 'shopping.filterAll', 'All'],
            ['pl', 'shopping.filterAll', 'Wszystkie'],
            ['en', 'shopping.filterActive', 'Active'],
            ['pl', 'shopping.filterActive', 'Aktywne'],
            ['en', 'shopping.filterArchived', 'Archived'],
            ['pl', 'shopping.filterArchived', 'Zarchiwizowane'],
            ['en', 'shopping.archived', 'Archived'],
            ['pl', 'shopping.archived', 'Zarchiwizowane'],
            ['en', 'shopping.items', 'items'],
            ['pl', 'shopping.items', 'produktów'],
            ['en', 'shopping.dueDate', 'Due:'],
            ['pl', 'shopping.dueDate', 'Termin:'],
            ['en', 'shopping.noDueDate', 'No due date'],
            ['pl', 'shopping.noDueDate', 'Brak terminu'],
            ['en', 'shopping.noProducts', 'No products'],
            ['pl', 'shopping.noProducts', 'Brak produktów'],
            ['en', 'shopping.noProductsYet', 'No products yet'],
            ['pl', 'shopping.noProductsYet', 'Brak produktów'],
            ['en', 'shopping.markAllBought', 'Mark all as purchased'],
            ['pl', 'shopping.markAllBought', 'Zaznacz wszystkie jako kupione'],
            ['en', 'shopping.weightPlaceholder', 'weight'],
            ['pl', 'shopping.weightPlaceholder', 'waga'],
            ['en', 'shopping.listNamePlaceholder', 'List name'],
            ['pl', 'shopping.listNamePlaceholder', 'Nazwa listy'],
            ['en', 'shopping.archive', 'Archive'],
            ['pl', 'shopping.archive', 'Archiwizuj'],
            ['en', 'shopping.restore', 'Restore'],
            ['pl', 'shopping.restore', 'Przywróć'],
            ['en', 'shopping.deleteTitle', 'Delete shopping list'],
            ['pl', 'shopping.deleteTitle', 'Usuń listę zakupów'],
            ['en', 'shopping.deleteMessage', 'Delete'],
            ['pl', 'shopping.deleteMessage', 'Usuń'],
            ['en', 'shopping.deleteWarning', 'This cannot be undone.'],
            ['pl', 'shopping.deleteWarning', 'Tej operacji nie da się cofnąć.'],
            ['en', 'shopping.leaveTitle', 'Leave without saving?'],
            ['pl', 'shopping.leaveTitle', 'Wyjść bez zapisu?'],
            ['en', 'shopping.leaveMessage', 'You have unsaved changes. Leave without saving?'],
            ['pl', 'shopping.leaveMessage', 'Masz niezapisane zmiany. Czy chcesz wyjść bez zapisu?'],
            ['en', 'shopping.leaveConfirm', 'Leave'],
            ['pl', 'shopping.leaveConfirm', 'Wyjdź'],
            ['en', 'shopping.share', 'Share'],
            ['pl', 'shopping.share', 'Udostępnij'],
            ['en', 'shopping.shareTitle', 'Share shopping list'],
            ['pl', 'shopping.shareTitle', 'Udostępnij listę zakupów'],
            ['en', 'shopping.shareList', 'Share list'],
            ['pl', 'shopping.shareList', 'Udostępnij listę'],
            ['en', 'shopping.addProduct', 'Add product'],
            ['pl', 'shopping.addProduct', 'Dodaj produkt'],
            ['en', 'shopping.addToList', 'Add to list'],
            ['pl', 'shopping.addToList', 'Dodaj do listy'],
            ['en', 'shopping.create', 'Create'],
            ['pl', 'shopping.create', 'Utwórz'],
            ['en', 'shopping.products', 'Products'],
            ['pl', 'shopping.products', 'Produkty'],
            ['en', 'shopping.removeProduct', 'Remove product'],
            ['pl', 'shopping.removeProduct', 'Usuń produkt'],
            ['en', 'shopping.productName', 'Product name'],
            ['pl', 'shopping.productName', 'Nazwa produktu'],
            ['en', 'shopping.productNamePlaceholder', 'e.g. Apples'],
            ['pl', 'shopping.productNamePlaceholder', 'np. Jabłka'],
            ['en', 'shopping.category', 'Category'],
            ['pl', 'shopping.category', 'Kategoria'],
            ['en', 'shopping.categoryNone', '— select —'],
            ['pl', 'shopping.categoryNone', '— wybierz —'],
            ['en', 'shopping.qty', 'Qty'],
            ['pl', 'shopping.qty', 'Ilość'],
            ['en', 'shopping.unit', 'Unit'],
            ['pl', 'shopping.unit', 'Jednostka'],
            ['en', 'shopping.viewAll', 'View all →'],
            ['pl', 'shopping.viewAll', 'Zobacz wszystkie →'],
            ['en', 'shopping.moreLists', 'more lists'],
            ['pl', 'shopping.moreLists', 'więcej list'],
            ['en', 'shopping.category.dairy', 'Dairy'],
            ['pl', 'shopping.category.dairy', 'Nabiał'],
            ['en', 'shopping.category.meat', 'Meat'],
            ['pl', 'shopping.category.meat', 'Mięso'],
            ['en', 'shopping.category.fruits', 'Fruits'],
            ['pl', 'shopping.category.fruits', 'Owoce'],
            ['en', 'shopping.category.vegetables', 'Vegetables'],
            ['pl', 'shopping.category.vegetables', 'Warzywa'],
            ['en', 'shopping.category.bakery', 'Bakery'],
            ['pl', 'shopping.category.bakery', 'Pieczywo'],
            ['en', 'shopping.category.beverages', 'Beverages'],
            ['pl', 'shopping.category.beverages', 'Napoje'],
            ['en', 'shopping.category.snacks', 'Snacks'],
            ['pl', 'shopping.category.snacks', 'Przekąski'],
            ['en', 'shopping.category.frozen', 'Frozen'],
            ['pl', 'shopping.category.frozen', 'Mrożonki'],
            ['en', 'shopping.category.spices', 'Spices'],
            ['pl', 'shopping.category.spices', 'Przyprawy'],
            ['en', 'shopping.category.household', 'Household'],
            ['pl', 'shopping.category.household', 'Dom'],
            ['en', 'shopping.category.hygiene', 'Hygiene'],
            ['pl', 'shopping.category.hygiene', 'Higiena'],
            ['en', 'shopping.category.other', 'Other'],
            ['pl', 'shopping.category.other', 'Inne'],
            ['en', 'shopping.unit.szt', 'pcs'],
            ['pl', 'shopping.unit.szt', 'szt'],
            ['en', 'shopping.unit.kg', 'kg'],
            ['pl', 'shopping.unit.kg', 'kg'],
            ['en', 'shopping.unit.g', 'g'],
            ['pl', 'shopping.unit.g', 'g'],
            ['en', 'shopping.unit.l', 'l'],
            ['pl', 'shopping.unit.l', 'l'],
            ['en', 'shopping.unit.ml', 'ml'],
            ['pl', 'shopping.unit.ml', 'ml'],
            ['en', 'shopping.unit.opak', 'pack'],
            ['pl', 'shopping.unit.opak', 'opak'],
            ['en', 'dashboard.title',   'Dashboard'],
            ['pl', 'dashboard.title',   'Panel'],
            ['en', 'dashboard.welcome', 'Welcome back'],
            ['pl', 'dashboard.welcome', 'Witaj z powrotem'],
            ['en', 'dashboard.welcomeBack', 'Welcome back'],
            ['pl', 'dashboard.welcomeBack', 'Witaj ponownie'],
            ['en', 'dashboard.overview', 'Here\'s your overview.'],
            ['pl', 'dashboard.overview', 'Oto Twój przegląd.'],
            ['en', 'dashboard.calendarTitle', 'Calendar'],
            ['pl', 'dashboard.calendarTitle', 'Kalendarz'],
            ['en', 'dashboard.openCalendar', 'Open calendar'],
            ['pl', 'dashboard.openCalendar', 'Otwórz kalendarz'],
            ['en', 'dashboard.calendarMonthCount', 'Events this month'],
            ['pl', 'dashboard.calendarMonthCount', 'Wydarzenia w tym miesiącu'],
            ['en', 'dashboard.guest', 'there'],
            ['pl', 'dashboard.guest', 'tam'],
            ['en', 'dashboard.reorderHint', 'Drag to reorder'],
            ['pl', 'dashboard.reorderHint', 'Przeciągnij, aby zmienić kolejność'],
            ['en', 'dashboard.resetTiles', 'Reset tile settings'],
            ['pl', 'dashboard.resetTiles', 'Resetuj ustawienia kafelków'],
            ['en', 'dashboard.scaleUp', 'Increase tile size'],
            ['pl', 'dashboard.scaleUp', 'Powiększ kafelek'],
            ['en', 'dashboard.scaleDown', 'Decrease tile size'],
            ['pl', 'dashboard.scaleDown', 'Pomniejsz kafelek'],
            ['en', 'dashboard.resizeHint', 'Drag to resize'],
            ['pl', 'dashboard.resizeHint', 'Przeciągnij, aby zmienić rozmiar'],
            ['en', 'dashboard.resetConfirmTitle', 'Reset tile settings?'],
            ['pl', 'dashboard.resetConfirmTitle', 'Zresetować ustawienia kafelków?'],
            ['en', 'dashboard.resetConfirmMessage', 'This will restore the default tile order and sizes.'],
            ['pl', 'dashboard.resetConfirmMessage', 'To przywróci domyślną kolejność i rozmiary kafelków.'],
            ['en', 'dashboard.resetConfirmAction', 'Reset'],
            ['pl', 'dashboard.resetConfirmAction', 'Resetuj'],
            ['en', 'dashboard.resetConfirmCancel', 'Cancel'],
            ['pl', 'dashboard.resetConfirmCancel', 'Anuluj'],
            ['en', 'events.pageTitle', '📅 My Events'],
            ['pl', 'events.pageTitle', '📅 Moje Wydarzenia'],
            ['en', 'events.viewList', 'List'],
            ['pl', 'events.viewList', 'Lista'],
            ['en', 'events.viewCalendar', 'Calendar'],
            ['pl', 'events.viewCalendar', 'Kalendarz'],
            ['en', 'events.add', 'Add Event'],
            ['pl', 'events.add', 'Dodaj wydarzenie'],
            ['en', 'events.addButton', '+ Add Event'],
            ['pl', 'events.addButton', '+ Dodaj wydarzenie'],
            ['en', 'events.missingManagePermission', 'Missing permission: events.manage'],
            ['pl', 'events.missingManagePermission', 'Brak uprawnienia: events.manage'],
            ['en', 'events.empty', 'No events yet. Click'],
            ['pl', 'events.empty', 'Brak wydarzeń. Kliknij'],
            ['en', 'events.emptySuffix', 'to create one.'],
            ['pl', 'events.emptySuffix', 'aby utworzyć pierwsze.'],
            ['en', 'events.viewAll', 'View all'],
            ['pl', 'events.viewAll', 'Zobacz wszystkie'],
            ['en', 'events.noUpcoming', 'No upcoming events.'],
            ['pl', 'events.noUpcoming', 'Brak nadchodzących wydarzeń.'],
            ['en', 'events.saveError', 'Failed to save event'],
            ['pl', 'events.saveError', 'Nie udało się zapisać wydarzenia'],
            ['en', 'events.deleteConfirm', 'Delete event'],
            ['pl', 'events.deleteConfirm', 'Usuń wydarzenie'],
            ['en', 'events.deleteError', 'Failed to delete event'],
            ['pl', 'events.deleteError', 'Nie udało się usunąć wydarzenia'],
            ['en', 'events.form.createTitle', 'New Event'],
            ['pl', 'events.form.createTitle', 'Nowe wydarzenie'],
            ['en', 'events.form.editTitle', 'Edit Event'],
            ['pl', 'events.form.editTitle', 'Edytuj wydarzenie'],
            ['en', 'events.form.titleLabel', 'Title *'],
            ['pl', 'events.form.titleLabel', 'Tytuł *'],
            ['en', 'events.form.titlePlaceholder', 'Event title'],
            ['pl', 'events.form.titlePlaceholder', 'Tytuł wydarzenia'],
            ['en', 'events.form.descriptionLabel', 'Description'],
            ['pl', 'events.form.descriptionLabel', 'Opis'],
            ['en', 'events.form.descriptionPlaceholder', 'Optional details…'],
            ['pl', 'events.form.descriptionPlaceholder', 'Opcjonalne szczegóły…'],
            ['en', 'events.form.startDateLabel', 'Start Date *'],
            ['pl', 'events.form.startDateLabel', 'Data rozpoczęcia *'],
            ['en', 'events.form.startTimeLabel', 'Start Time'],
            ['pl', 'events.form.startTimeLabel', 'Godzina rozpoczęcia'],
            ['en', 'events.form.endDateLabel', 'End Date'],
            ['pl', 'events.form.endDateLabel', 'Data zakończenia'],
            ['en', 'events.form.endTimeLabel', 'End Time'],
            ['pl', 'events.form.endTimeLabel', 'Godzina zakończenia'],
            ['en', 'events.form.locationLabel', 'Location (Poland)'],
            ['pl', 'events.form.locationLabel', 'Lokalizacja (Polska)'],
            ['en', 'events.form.saveChanges', 'Save Changes'],
            ['pl', 'events.form.saveChanges', 'Zapisz zmiany'],
            ['en', 'calendar.pageTitle', 'Calendar'],
            ['pl', 'calendar.pageTitle', 'Kalendarz'],
            ['en', 'calendar.clickEmptyToCreate', 'Click empty slot to create event'],
            ['pl', 'calendar.clickEmptyToCreate', 'Kliknij pusty slot, aby dodać wydarzenie'],
            ['en', 'calendar.allDay', 'All day'],
            ['pl', 'calendar.allDay', 'Cały dzień'],
            ['en', 'calendar.previous', 'Previous'],
            ['pl', 'calendar.previous', 'Poprzedni'],
            ['en', 'calendar.next', 'Next'],
            ['pl', 'calendar.next', 'Następny'],
            ['en', 'calendar.today', 'Today'],
            ['pl', 'calendar.today', 'Dziś'],
            ['en', 'calendar.month', 'Month'],
            ['pl', 'calendar.month', 'Miesiąc'],
            ['en', 'calendar.week', 'Week'],
            ['pl', 'calendar.week', 'Tydzień'],
            ['en', 'calendar.day', 'Day'],
            ['pl', 'calendar.day', 'Dzień'],
            ['en', 'calendar.agenda', 'Agenda'],
            ['pl', 'calendar.agenda', 'Agenda'],
            ['en', 'calendar.date', 'Date'],
            ['pl', 'calendar.date', 'Data'],
            ['en', 'calendar.time', 'Time'],
            ['pl', 'calendar.time', 'Godzina'],
            ['en', 'calendar.event', 'Event'],
            ['pl', 'calendar.event', 'Wydarzenie'],
            ['en', 'calendar.emptyRange', 'No events in this range.'],
            ['pl', 'calendar.emptyRange', 'Brak wydarzeń w tym zakresie.'],
            ['en', 'translations.title',         'Translation Keys'],
            ['pl', 'translations.title',         'Klucze tłumaczeń'],
            ['en', 'translations.add',           '+ Add Translation'],
            ['pl', 'translations.add',           '+ Dodaj tłumaczenie'],
            ['en', 'translations.keyCol',        'Key'],
            ['pl', 'translations.keyCol',        'Klucz'],
            ['en', 'translations.localeCol',     'Locale'],
            ['pl', 'translations.localeCol',     'Język'],
            ['en', 'translations.valueCol',      'Value'],
            ['pl', 'translations.valueCol',      'Wartość'],
            ['en', 'translations.actionsCol',    'Actions'],
            ['pl', 'translations.actionsCol',    'Akcje'],
            ['en', 'translations.empty',         'No translations found.'],
            ['pl', 'translations.empty',         'Brak tłumaczeń.'],
            ['en', 'translations.filterLocale',  'Filter by locale'],
            ['pl', 'translations.filterLocale',  'Filtruj po języku'],
            ['en', 'translations.saveBtn',       'Save'],
            ['pl', 'translations.saveBtn',       'Zapisz'],
            ['en', 'translations.cancelBtn',     'Cancel'],
            ['pl', 'translations.cancelBtn',     'Anuluj'],
            ['en', 'translations.deleteConfirm', 'Delete this translation?'],
            ['pl', 'translations.deleteConfirm', 'Usunąć to tłumaczenie?'],
            ['en', 'common.loading',  'Loading…'],
            ['pl', 'common.loading',  'Ładowanie…'],
            ['en', 'common.error',    'An error occurred'],
            ['pl', 'common.error',    'Wystąpił błąd'],
            ['en', 'common.save',     'Save'],
            ['pl', 'common.save',     'Zapisz'],
            ['en', 'common.cancel',   'Cancel'],
            ['pl', 'common.cancel',   'Anuluj'],
            ['en', 'common.delete',   'Delete'],
            ['pl', 'common.delete',   'Usuń'],
            ['en', 'common.edit',     'Edit'],
            ['pl', 'common.edit',     'Edytuj'],
            ['en', 'common.confirm',  'Confirm'],
            ['pl', 'common.confirm',  'Potwierdź'],
            ['en', 'common.yes',      'Yes'],
            ['pl', 'common.yes',      'Tak'],
            ['en', 'common.no',       'No'],
            ['pl', 'common.no',       'Nie'],
            ['en', 'common.close',    'Close'],
            ['pl', 'common.close',    'Zamknij'],
            ['en', 'common.add',      'Add'],
            ['pl', 'common.add',      'Dodaj'],
            ['en', 'common.back',     '← Back'],
            ['pl', 'common.back',     '← Wróć'],
            ['en', 'common.saving',   'Saving…'],
            ['pl', 'common.saving',   'Zapisywanie…'],
            ['en', 'common.showMore', 'Show more'],
            ['pl', 'common.showMore', 'Pokaż więcej'],
            ['en', 'common.showLess', 'Show less'],
            ['pl', 'common.showLess', 'Pokaż mniej'],
            ['en', 'common.viewAll', 'View all'],
            ['pl', 'common.viewAll', 'Zobacz wszystkie'],
            ['en', 'common.more', 'more'],
            ['pl', 'common.more', 'więcej'],
            ['en', 'common.completed', 'completed'],
            ['pl', 'common.completed', 'ukończone'],
            ['en', 'common.previous', 'Previous'],
            ['pl', 'common.previous', 'Poprzednia'],
            ['en', 'common.next', 'Next'],
            ['pl', 'common.next', 'Następna'],
            ['en', 'common.page', 'Page'],
            ['pl', 'common.page', 'Strona'],
            ['en', 'common.pagination', 'Pagination'],
            ['pl', 'common.pagination', 'Paginacja'],
            ['en', 'common.jumpToPage', 'Jump to page'],
            ['pl', 'common.jumpToPage', 'Przejdź do strony'],
            ['en', 'common.go', 'Go'],
            ['pl', 'common.go', 'Przejdź'],
            ['en', 'common.search',   'Search'],
            ['pl', 'common.search',   'Szukaj'],
            ['en', 'shopping.dueDateLabel', 'Due date (optional)'],
            ['pl', 'shopping.dueDateLabel', 'Termin (opcjonalnie)'],
            ['en', 'common.fieldRequired', 'This field is required'],
            ['pl', 'common.fieldRequired', 'To pole jest wymagane'],
            ['en', 'common.edit', 'Edit'],
            ['pl', 'common.edit', 'Edytuj'],
            ['en', 'shopping.print', 'Print'],
            ['pl', 'shopping.print', 'Drukuj'],
            ['en', 'shopping.bought', 'bought'],
            ['pl', 'shopping.bought', 'kupione'],
        ];

        $groupIds = [];
        foreach ($translations as [$locale, $key, $value]) {
            if (!isset($groupIds[$key])) {
                $escapedKey = str_replace("'", "\\'", $key);
                $this->addSql(
                    "INSERT IGNORE INTO translation_group (translation_key, created_at, updated_at) VALUES ('{$escapedKey}', '{$now}', '{$now}')"
                );

                $groupIds[$key] = true;
            }
        }

        foreach ($translations as [$locale, $key, $value]) {
            $escapedValue = str_replace("'", "\\'", $value);
            $escapedKey = str_replace("'", "\\'", $key);
            $this->addSql(
                "INSERT IGNORE INTO translation (translation_group_id, locale, translation_value, created_at, updated_at) "
                . "SELECT id, '{$locale}', '{$escapedValue}', '{$now}', '{$now}' "
                . "FROM translation_group WHERE translation_key = '{$escapedKey}'"
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE translation');
        $this->addSql('DROP TABLE translation_group');
    }
}
