#!/bin/sh
set -e

echo "=== Translation Service: Waiting for MySQL ==="
DB_URL="${DATABASE_URL:-mysql://app:secret@mysql:3306/translations}"
DB_HOST=$(echo "$DB_URL" | sed -E 's|.*@([^:/]+).*|\1|')
DB_PORT=$(echo "$DB_URL" | sed -E 's|.*:([0-9]+)/.*|\1|')
DB_NAME=$(echo "$DB_URL" | sed -E 's|.*/([^?]+).*|\1|')
DB_USER=$(echo "$DB_URL" | sed -E 's|.*://([^:]+):.*|\1|')
DB_PASS=$(echo "$DB_URL" | sed -E 's|.*://[^:]+:([^@]+)@.*|\1|')
until php -r "new PDO('mysql:host=${DB_HOST};port=${DB_PORT};dbname=${DB_NAME}', '${DB_USER}', '${DB_PASS}');" 2>/dev/null; do
    echo "  MySQL (${DB_NAME}) not ready, retrying in 2s..."
    sleep 2
done
echo "=== MySQL (${DB_NAME}) is ready ==="

echo "=== Waiting for JWT public key (generated by auth-service) ==="
while [ ! -f /app/config/jwt/public.pem ]; do
    echo "  JWT public key not yet available, retrying in 2s..."
    sleep 2
done
echo "=== JWT public key found ==="

cd /app

needs_composer_install() {
    if [ ! -f vendor/autoload.php ]; then
        return 0
    fi

    php -r "require 'vendor/autoload.php';" >/dev/null 2>&1 || return 0
    return 1
}

if needs_composer_install; then
    echo "Installing dependencies..."
    composer install --no-interaction --optimize-autoloader
fi

php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration || true
php bin/console cache:clear || true

echo "=== Translation Service is ready ==="
exec "$@"
